### ISSUE TITLE
Add log viewer to settings page

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#100]
This will help troubleshooting issues so customer doesn't have to dig into the Plugin editor. Also, will  help if the plugin editor is deactivated.

**Comment by tnorthcutt** [comment]
👏 Might be worth looking at how Restrict Content Pro does this; their implementation is simple but works well.

**Comment by tnorthcutt** [comment]
Added in https://github.com/ConvertKit/ConvertKit-WordPress/pull/150
