### ISSUE TITLE
Saving ConvertKit Contact Form 7 mapping does not stick

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#107]
To recreate: 
WordPress 4.9.6
ConvertKit for WordPress 1.5.5
Contact Form 7 5.0.2

1. Setup a CF7 form
2. Add ConvertKit API key
3. Go to Settings > ConvertKit, click Contact Form 7 tab
4. Select a form to map to the CF7 form to and press Save
5. The select clears.

Check db for `select * from wp_options where option_name like '% _wp_convertkit_integration_contactform7_settings%'`
The option_value is "       2"

**Comment by tnorthcutt** [comment]
Fixed by https://github.com/ConvertKit/ConvertKit-WordPress/pull/137
