### ISSUE TITLE
Version 1.5.4 > Blog Category Bug/Conflict

### ISSUE THREAD

**Issue by BusinessBloomer** [ConvertKit/ConvertKit-WordPress#108]
There is a conflict between ConvertKit plugin Version 1.5.4 and the latest WordPress. Here's a screenshot: https://www.screencast.com/t/IirSDNmPKba

Description of the bug: this conflict duplicates the "Edit Category" description textarea. Both are unsaveable and the Text/Visual tab switch is broken

**Comment by growdev** [comment]
@BusinessBloomer this will be fixed in version 1.6.3.
