### ISSUE TITLE
Unable to change blog category form to None

### ISSUE THREAD

**Issue by gregmount** [ConvertKit/ConvertKit-WordPress#110]
Once a CK form has been set for a blog category, it is not possible to change back to None.

Steps to reproduce:

1. Edit a category, add a form and update.
2. Refresh page to confirm that form is selected.
3. Edit the category again, change form selection to None and update.

Previous selection remains active.

**Comment by gregmount** [comment]
Something like this in class-convertkit-settings.php (starting at line 301) would sort it out:

```
/**
  * Set the default ConvertKit form for
  *
  * @param int $tag_id
  */
public function save_category_fields( $tag_id ) {
  $ck_default_form = isset( $_POST['ck_default_form'] ) ? intval( $_POST['ck_default_form']  ) : 0;
  if ( $ck_default_form ) {
    update_term_meta( $tag_id, 'ck_default_form', $ck_default_form );
  } else {
    update_term_meta( $tag_id, 'ck_default_form', 'default' );
  }
}
```

**Comment by tnorthcutt** [comment]
Thanks, @gregmount! This will be shipped in an upcoming release (likely within the next week or two).
