### ISSUE TITLE
Yoast Compat

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#115]
Follow up on this:
https://github.com/Yoast/wordpress-seo/issues/10215

respond to customer:
https://secure.helpscout.net/conversation/611701049/238768/?folderId=956509
https://secure.helpscout.net/conversation/633581227/255748?folderId=956509
https://wordpress.org/support/topic/default-form-for-category-problem/
https://secure.helpscout.net/conversation/677887227/280921?folderId=956509

**Comment by tnorthcutt** [comment]
Reopening b/c still reported: https://github.com/Yoast/wordpress-seo/issues/10215
