### ISSUE TITLE
Undefined notice 

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#120]
"PHP Notice:  Undefined index:  in /app/public/wp-content/plugins/convertkit/includes/class-convertkit.php on line 265"

This happens because $landing_page_id is empty.

**Update**

This is still happening in v 1.6.2

update when fixed:
https://secure.helpscout.net/conversation/695907738/289964?folderId=956509

**Comment by tnorthcutt** [comment]
Update when fixed: https://secure.helpscout.net/conversation/756021332/321000/

**Comment by tnorthcutt** [comment]
Update when fixed: https://secure.helpscout.net/conversation/752091761/319195/

**Comment by tnorthcutt** [comment]
Closed in https://github.com/ConvertKit/ConvertKit-WordPress/issues/175
