### ISSUE TITLE
Add opt-in function to collect metrics on versions that are running

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#121]
Work within the w.org guidelines to add an opt-in function to collect metrics on versions of the plugin that are active.

**Comment by dylanfeltus** [comment]
@growdev Where would this data be reported to? Can we send it to segment?

**Comment by growdev** [comment]
@dylanfeltus 
> Where would this data be reported to?
That's TBD.

> Can we send it to segment?
Yes, probably via the API.
