### ISSUE TITLE
Send data to CK support

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#122]
- [ ] Add a way for customers to report site data to CK Support
This would be a button in the admin settings labeled "Send site data to CK Support"

The data might include:
- Plugin version
- curl version
- mbstring installed
- other plugins installed
- active theme
- ping test to api.convertkit.com
- api key

**Comment by dylanfeltus** [comment]
@growdev where and when would this data be sent?

**Comment by growdev** [comment]
@dylanfeltus The idea behind this was to have a way for customers to automate sending site data to CK support (Help Scout) for troubleshooting support request.. Currently it takes some back and forth in a ticket or on live chat to get this information. Adding a
