### ISSUE TITLE
Do not do ajax call if there is no subscriber_id

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#128]
1. Retest the scenario to verify.
2. Verify that no call is made if it is not necessary.

Related: #127

ref: https://wordpress.org/support/topic/admin-ajax-php-long-loading-time/

**Comment by tnorthcutt** [comment]
Closing in favor of #127 which will be closed by https://github.com/ConvertKit/ConvertKit-WordPress/pull/162
