### ISSUE TITLE
Purchase: Not same PID for what seems to be the same product

### ISSUE THREAD

**Issue by pothibo** [ConvertKit/ConvertKit-WordPress#130]
Seems like this customer: https://secure.helpscout.net/conversation/691293297/287772?folderId=948198 has problem with his worpdress plugin. Looking at the PID for all products, it seems that the PIDs are vastly different and one of those product that got in was from Oct 25 with the plugin set at 1.0.6

**Comment by growdev** [comment]
@pothibo I'm moving this to the appropriate repo.
