### ISSUE TITLE
CF7 Integration

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#134]
Contact Form 7 version 5.0.5
ConvertKit 1.6.2

Steps to recreate:

1. Add several contact forms in CF7
2. Go to Settings > ConvertKit > CF7 tab
3. Change ConvertKit form to any form
4. Press Save Changes. 
5. Changes are not saved.

ref: https://secure.helpscout.net/conversation/698150273/291176?folderId=956509

**Comment by dylanfeltus** [comment]
@growdev Duplicate of #107?

**Comment by tnorthcutt** [comment]
Fixed by https://github.com/ConvertKit/ConvertKit-WordPress/pull/137
