### ISSUE TITLE
Refactor to use ConvertKit's PHP library

### ISSUE THREAD

**Issue by tnorthcutt** [ConvertKit/convertkit-wordpress#145]
Currently, this plugin uses a built-in class to connect to the ConvertKit API. It would make a lot of sense to standardize on using [ConvertKit's PHP library](https://github.com/ConvertKit/ConvertKitSDK-PHP) instead.

This will be a significant refactoring; proceed with care.

**Comment by tnorthcutt** [comment]
Will need to consider how we handle logging. Currently the API implementation in this plugin is sprinkled with calls to `WP_ConvertKit::log()`. We'd need to decouple that in order to use the PHP library instead.

**Comment by tnorthcutt** [comment]
Note: the  ConvertKit PHP library requires PHP >= 5.5, so before doing this we'd need to decide if that's acceptable.

**Comment by ggwicz** [comment]
Migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todos/3256109009

Closing this for now!
