### ISSUE TITLE
Need to be able to refresh data from ConvertKit in all relevant locations

### ISSUE THREAD

**Issue by tnorthcutt** [ConvertKit/convertkit-wordpress#164]
E.g. on the page/post edit screen, the ConvertKit metabox has a list of forms, landing pages, and tags. This list can be refreshed by using the `Refresh forms` button in the ConvertKit settings area, but that's very unintuitive.

If a user is editing a page, goes to their ConvertKit account to add a tag, then comes back the page, they should be able to use the new tag without visiting the settings page.

 ![image](https://user-images.githubusercontent.com/796639/51699949-389ac500-1fcb-11e9-9ae1-4687f160d70c.png)

**Comment by ggwicz** [comment]
Migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todos/3256106408

Closing this here for now!
