### ISSUE TITLE
Allow setting a default form for all registered post types and taxonomies

### ISSUE THREAD

**Issue by tnorthcutt** [ConvertKit/convertkit-wordpress#165]
E.g. WooCommerce products, LMS courses or lessons, custom taxonomies, etc.

- [ ] Fetch all registered (public) post types, and display checkboxes for them on the settings page
- [ ] In `WP_ConvertKit::append_form()`, append if post type is checked in settings

**Comment by tnorthcutt** [comment]
Update when complete: https://app.intercom.io/a/apps/e4n3xtxz/inbox/inbox/2911962/conversations/21399399612

**Comment by tnorthcutt** [comment]
Done for WooCommerce products in #218

**Comment by ggwicz** [comment]
migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todos/3254734344

closing here for now!
