### ISSUE TITLE
Plugin performance issues

### ISSUE THREAD

**Issue by tnorthcutt** [ConvertKit/convertkit-wordpress#175]
https://app.intercom.io/a/apps/e4n3xtxz/inbox/inbox/conversation/20788691567

Customer reports many duplicate API calls showing in Query Monitor:
https://downloads.intercomcdn.com/i/o/102588102/c13e3aeec9b21e9b1edd6b9e/Screen+Shot+2019-02-11+at+8.08.13+PM.png
https://downloads.intercomcdn.com/i/o/102588116/38965b75e7d64b2ad83c1bc6/Screen+Shot+2019-02-11+at+8.17.22+PM.png

**Comment by tnorthcutt** [comment]
Likely related: https://github.com/ConvertKit/ConvertKit-WordPress/issues/103

**Comment by tnorthcutt** [comment]
Similar case: https://app.intercom.io/a/apps/e4n3xtxz/inbox/inbox/conversation/23703698659

Ideally, the subscriber lookup would happen async and not delay page rendering.

**Comment by ggwicz** [comment]
migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todos/3254725514

closing this issue for now!
