### ISSUE TITLE
Add new shortcode for API v3 form ids, maintain backwards compatibility with old shortcode.

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#18]
The shortcode `[convertkit]` is used to insert forms in the middle of content on posts/pages with the metabox Form dropdown set to "None".

It would be good to add a shortcode attribute to choose the form to be displayed instead of just using the global default form setting.

ref: https://wordpress.org/support/topic/form-specific-shortcode?replies=2

**Comment by marcboquet** [comment]
We have a `[convertkit form=12345]` shortcode currently, we show instructions in the form embed settings in CK:
![Uploading Screen Shot 2016-05-17 at 19.20.05.png…]()

For 1.4.1 though we'll need to keep backwards compatibility, so the `[convertkit form=12345]` will need to change to use API v2, and we'll add another shortcode `[convertkit id=123]` which will use API v3.

We'll update the settings page in CK so all new users will use v3, but old shortcodes need to keep working.

**Comment by growdev** [comment]
Backwards compatibility maintained and `shortcode()` method cleaned up to be easier to read: https://github.com/ConvertKit/ConvertKit-WordPress/blob/1.4.1/wp-convertkit.php#L217

**Comment by growdev** [comment]
Fixed in 1.4.1
