### ISSUE TITLE
Default form set in plugin but it's showing a different form on the page or post

### ISSUE THREAD

**Issue by enonevets** [ConvertKit/ConvertKit-WordPress#180]
New Ticket:
https://app.intercom.io/a/apps/e4n3xtxz/inbox/inbox/2906644/conversations/20966014198

Old Ticket:
https://secure.helpscout.net/conversation/621042102/245806/

WP Login:
https://www.helpspot.com/vault/9H8EgcKPYzTH4Lj6LllID0BJ3mlrjxrCgq6NOTK8
PASSWORD:  iPrvizs43ssb

Issue:
Plugin has a default form chosen. Page has the selection show "default form". A different form appears on the page instead of the default form chosen in plugin settings.

Page:
https://peterakkies.net/wasted-time/

**Comment by tnorthcutt** [comment]
_Closed; was opened in wrong repo._
