### ISSUE TITLE
Consider adding html comments before and/or after inserted forms

### ISSUE THREAD

**Issue by tnorthcutt** [ConvertKit/convertkit-wordpress#194]
It seems somewhat common in support tickets for there to be a lack of clarity about whether forms are placed by the ConvertKit plugin, or by using the js or html embed options, or the shortcode.

For forms placed by the plugin, whether via a regular post/page form or via a shortcode, we could prepend or append (or both) an html comment to add clarity:
`<!-- This form inserted by the ConvertKit plugin -->`
`<!-- This form inserted by the ConvertKit plugin; shortcode -->`

**Comment by ggwicz** [comment]
Migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todos/3254605779

Closing here
