### ISSUE TITLE
Consider if/how the tagging feature is useful

### ISSUE THREAD

**Issue by tnorthcutt** [ConvertKit/convertkit-wordpress#197]
@dylanfeltus for us to chat about when you're back 😄 

Relevant Slack thread: https://convertkit.slack.com/archives/C526RG58S/p1555818426420600?thread_ts=1555535535.278800&cid=C526RG58S

Customer wonders how/why they should use the plugin tagging feature, since it relies on people clicking email links, and those can be used to apply a tag independently of the plugin.

N.B. it also works for cookied visitors, e.g. who have filled out an on-site form and thus have a cookie set with their subscriber ID. But since that isn't 100% reliable, customers may wonder about the utility of this...

It would be helpful for me to understand the original motivations behind this feature, so we can assess how useful it is and if there are improvements we can make.

**Comment by ggwicz** [comment]
migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todos/3254717995

closing here for now!
