### ISSUE TITLE
Convert default form id to v3 format in upgrade function

### ISSUE THREAD

**Issue by marcboquet** [ConvertKit/ConvertKit-WordPress#21]
If we are upgrading from <1.4.0 we should convert the default form id to the new api v3 form id.

We'll add a method in the api to deal with that.

**Comment by growdev** [comment]
The `upgrade()` function handles updating `id` to `form_id`

https://github.com/ConvertKit/ConvertKit-WordPress/blob/1.4.1/wp-convertkit.php#L404

**Comment by growdev** [comment]
Fixed in 1.4.1
