### ISSUE TITLE
Contact Form 7 custom field compatibility

### ISSUE THREAD

**Issue by tnorthcutt** [ConvertKit/convertkit-wordpress#223]
Customer is interested in the ability to send e.g. the title of the post a form is embedded in to ConvertKit as a custom field: https://app.intercom.io/a/apps/e4n3xtxz/inbox/inbox/3066130/conversations/23772417899

**Comment by ggwicz** [comment]
migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todos/3254712958

closing this here for now!
