### ISSUE TITLE
Don't request all forms on get_form_embed

### ISSUE THREAD

**Issue by marcboquet** [ConvertKit/ConvertKit-WordPress#23]
We're requesting all forms in the `get_form_embed` method, which is called on every page load: https://github.com/ConvertKit/ConvertKit-WordPress/blob/47293186769d87c27da7c2d351e4e767c8f71b95/wp-convertkit.php#L304-L310

Since it won't be showing an error anymore if the form is not available I think we can remove this extra request.

**Comment by growdev** [comment]
Fixed in 1.4.1
