### ISSUE TITLE
Confusing wording on post/page settings "Add a tag" setting

### ISSUE THREAD

**Issue by tnorthcutt** [ConvertKit/convertkit-wordpress#231]
This is what the post/page metabox currently looks like:

![CleanShot 2020-03-26 at 07 25 06@2x](https://user-images.githubusercontent.com/796639/77651897-1126eb80-6f33-11ea-885a-d6f5d79c09d6.png)

The "Add a tag" setting can easily be confusing, because it implies that anyone who visits this page (or in the case of a landing page, possibly anyone who fills out the form) will have this tag applied. That isn't the case; this setting works in concert with the in-app `ck_subscriber_id` setting to tag visitors who arrive via an in-email link:

<img width="1123" alt="CleanShot 2020-03-26 at 07 27 36@2x" src="https://user-images.githubusercontent.com/796639/77652054-492e2e80-6f33-11ea-9791-e6556d65c13e.png">

We should improve the metabox copy to more clearly indicate this relationship/dependency.

**Comment by ggwicz** [comment]
migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todos/3254643675

closing here for now!
