### ISSUE TITLE
Set subscriber cookie regardless of what page they land on 

### ISSUE THREAD

**Issue by tnorthcutt** [ConvertKit/convertkit-wordpress#233]
Currently, our javascript only sets a cookie if the visitor lands on a page that has a "tag visitors to this page" tag set: https://github.com/ConvertKit/ConvertKit-WordPress/blob/f5a17a48cd688afb2dc01017cf24b14f7139269a/resources/frontend/wp-convertkit.js#L25

Instead, we should set the cookie regardless, so that if they then later navigate to a "tagging" page, they'll get tagged.

**Comment by ggwicz** [comment]
Migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todolists/3254599120

closing here for now
