### ISSUE TITLE
Shortcode backwards compatibility

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#25]
I need some feedback and guidance on how to handle the use of shortcodes in this plugin to display forms.

### Version 1.3.9 
These are possible uses of the plugin's shortcode. Both of these uses requires the ConvertKit meta box on that page to have Form set to "None" and Landing Page set to "None" like this:
![screen shot 2016-06-06 at 1 08 31 pm](https://cloud.githubusercontent.com/assets/290886/15832421/c84aca9a-2be7-11e6-9e11-ef27e5fbbf95.png)

1. The `[convertkit]` shortcode added to a post or page will add the global Default Form to the content. If the Default Form setting is "None" no form is added.

2. If the shortcode is used with an attribute of `form` then the specific form is added to the page. This attribute expects the `V2` ID  Example: `[convertkit form='4835722']`
If the form argument does not match up with a form in the result from a call to `ConvertKitAPI::get_resources()` no form is shown.

### Version 1.4.1

Version 1.4.1 introduces `V3` API calls to the `ConvertKitAPI` class.  The method [`ConvertKitAPI::_get_api_responses()`](https://github.com/ConvertKit/ConvertKit-WordPress/blob/master/lib/convertkit-api.php#L172) now uses a `V3` endpoint.

1. The proposed shortcode update is to add an argument of `id` that would be the `V3` `form_id`. 
Example: `[convertkit id='23887']`

2. It is problematic to scan all posts and page content for shortcodes using the `form` attribute. To maintain backwards compatibility for any customers using the `form` attribute the API should keep a `V2` endpoint call for getting the form markup.

3. Going forward these will be valid shortcode uses:
`[convertkit]`     Display global form using a `V3` form_id.
`[convertkit form='99999999']`     Display specific form using a `V2` ID.
`[convertkit id='99999']`     Display specific form using a `V3` form_id.

### Questions

1. Does what I've outlined sound correct?
2. `WP_ConvertKit::get_form_embed()` needs some refactoring to handle these cases and it's where I'm getting hung up.
3. I don't know if any of the attribute uses are documented either on wordpress.org or on CK.com. Is that true?
4. (Based on answer from previous question) Do you have any idea of the number of customers impacted by the changes to shortcode attributes?

**Comment by marcboquet** [comment]
The outline sounds good, thanks for documenting it!
As far as I know the only place where the attribute is documented is in the form embed settings in the CK app, where we show the different options of embedding the form.
Not sure how many customers are using the shortcodes, but a large percentage of our customers use the WordPress plugin, so I'm sure the number is not insignificant.

I left [a comment](https://github.com/ConvertKit/ConvertKit-WordPress/pull/20/files#r66126002) in the PR, my thinking is that if we handle the 3 scenarios separately it will be easier to deal with.
So we'll have "shortcode with `id`", "shortcode with `form`" and "default shortcode".

Then, for the default shortcode we could use a persisted setting that would tell if the default form id is V2 or V3. I'm thinking of something like `default_form_v3` which will set to `true` the first time they save their settings from the plugin admin.
So from the `get_form_embed()` code we can check for that being present and we'll know to use V3. If it's not present we'll use V2.

Does this make sense?

**Comment by growdev** [comment]
Great, thanks for the feedback @marcboquet.

Some further explanation about changes I'm making:

There are 3 ways forms are added to the WordPress pages:

1. Appended to the content based on the Form metabox setting
2. Shortcode
3. Landing page takeover based on the Landing Page metabox setting

1 and 2 use the same `wp_convertkit_get_form()` helper function which calls a static method in the `WP_ConvetKit` class. 

This is confusing and does not make it easy =to keep the `V2` call for the Shortcode so I'm going to change the callback for 1. Append to handle the embed without using the helper function.

**Comment by growdev** [comment]
Fixed in 1.4.1
