### ISSUE TITLE
 PHP Deprecated:  Required parameter $user_email follows optional parameter $subscriber_id

### ISSUE THREAD

**Issue by danielmerriott** [ConvertKit/convertkit-wordpress#260]
I'm seeing the following in WP Debug log:

`PHP Deprecated:  Required parameter $user_email follows optional parameter $subscriber_id in /public_html/wp-content/plugins/convertkit/includes/class-convertkit-custom-content.php on line 358`

**Comment by n7studios** [comment]
Fixed in 1.9.6.
