### ISSUE TITLE
Select2 custom styles are not scoped and break other instances

### ISSUE THREAD

**Issue by JiveDig** [ConvertKit/convertkit-wordpress#287]
The min-width declaration is causing side-scroll in any ACF (or other) block that uses a select2 field in the block setting sidebar. Unrelated - but your CSS url has a double `//` in it as well.

<img width="338" alt="158414384-cf603c89-e413-414b-b964-afb1a852a77a" src="https://user-images.githubusercontent.com/540990/158465444-3d14ec69-c181-499e-85f7-42020b424b88.png">

<img width="511" alt="158465083-79d995a5-236a-4865-afde-b02ea33a4a16" src="https://user-images.githubusercontent.com/540990/158465469-afb217cc-6e95-4990-b950-7e56bc8a038b.png">

<img width="508" alt="158465166-af6c74e4-9177-4e44-a144-7a1cd1cb8b08" src="https://user-images.githubusercontent.com/540990/158465491-11851ca1-2fa3-4e96-8929-0df7af00ece6.png">

**Comment by n7studios** [comment]
@JiveDig Thanks for the report. Aiming to resolve by end of Thursday in the next Plugin update.

**Comment by JiveDig** [comment]
TY!

**Comment by n7studios** [comment]
Resolved in 1.9.7.0, available at https://en-gb.wordpress.org/plugins/convertkit/
