### ISSUE TITLE
Add logger

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#35]
The plugin needs a logger to capture:
- [x]  Error messages when unable to connect to the CK API
- [x]  Data sent/received with API
- [x]  Other API related data

**Comment by menasheh** [comment]
Logging was added but not very effective.  It needs to log more.

**Comment by growdev** [comment]
Added in #36

**Comment by menasheh** [comment]
@growdev None of these things were being properly logged in my install.  This update you used to close it was from 2 months ago, what changed now?
