### ISSUE TITLE
Broken Convertkit Form Displays Random ASCII Characters

### ISSUE THREAD

**Issue by menasheh** [ConvertKit/ConvertKit-WordPress#39]
I used the plugin "All in One WP Migration" to migrate a WP install from one site to another.  Now [my site](https://peromsik.com/blog) displays beautiful characters instead of the form:

![image](https://cloud.githubusercontent.com/assets/1890286/20609388/c4cfa694-b259-11e6-9178-734db98e083c.png)

The plugin isn't able to contact the API:

![image](https://cloud.githubusercontent.com/assets/1890286/20609407/0dbaf9f8-b25a-11e6-9caf-b088f40fd42a.png)

Also, uninstalling the convertkit plugin doesn't clear it's data.  Upon a new install, my API and secret keys were already set up.

A curl command run from the server does retrieve the proper response.

What's changed?

php versions and mysql versions updated - php v 7.0 now.

The plugin's logging features leave much to be desired.

As a temporary fix, I've copied in the html of the sidebar form from the old site.  However, I've left the widget below as a demonstration.  It would also be nice to have the post-post forms working automatically...

**Comment by menasheh** [comment]
I tested this on a fresh install using the same server, and the forms just didn't show.

**Comment by menasheh** [comment]
Also tested switch to php5.6, no difference.

**Comment by growdev** [comment]
Since it's an issue with a migration plugin it is more of a support issue. This is the only report of the issue, if more customers report will reopen it.

**Comment by menasheh** [comment]
@growdev **uninstalling the convertkit plugin doesn't clear it's data. Upon a new install, my API and secret keys were already set up.**

Support isn't going to fix this, and code changes could.
