### ISSUE TITLE
Associate forms with a category?

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#41]
Add a way to map categories to forms so that any post in that category would have the form added to it.

reference: https://wordpress.org/support/topic/associate-a-form-with-a-category/

**Comment by dylanfeltus** [comment]
https://nextplease.io/requests/482

**Comment by tnorthcutt** [comment]
Seems like this was added in https://github.com/ConvertKit/ConvertKit-WordPress/pull/96

@growdev does that sound right to you?

**Comment by tnorthcutt** [comment]
Confirmed this was added; closing.
