### ISSUE TITLE
Research if/elseif/then for Shortcode

### ISSUE THREAD

**Issue by growdev** [ConvertKit/convertkit-wordpress#80]
Possibly useful:
https://wordpress.org/plugins/if-shortcode/

ref: https://secure.helpscout.net/conversation/536247583/184040/?folderId=936324

**Comment by dylanfeltus** [comment]
https://nextplease.io/requests/154

**Comment by ggwicz** [comment]
Migrated to basecamp: https://3.basecamp.com/3650415/buckets/10356988/todos/3256115508

Closing for now
