### ISSUE TITLE
Research TinyMCE settings getting messed with

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#85]
CK tags get loaded for TinyMCE, but in some instances they get cleared. Research plugin combinations from customer site that might cause this.  

ref: https://convertkit.slack.com/archives/C0KELUXBK/p1510774724000442
ref: https://secure.helpscout.net/conversation/465266853/133982?folderId=936326
Another one: https://secure.helpscout.net/conversation/479903209/142827/
https://secure.helpscout.net/conversation/493072914/150485?folderId=956509
ref: https://secure.helpscout.net/conversation/508078989/160317?folderId=956509
another one :key: https://secure.helpscout.net/conversation/508078989/160317?folderId=956509

**Comment by growdev** [comment]
I wasn't able to recreate this with the plugins loaded on customer's site. I'll keep this open in case it surfaces again.

**Comment by growdev** [comment]
Ref: https://secure.helpscout.net/conversation/618798864/244063?folderId=936326

Still an issue. 

Plugins on this site:
<img width="668" alt="add new page rhoda design studio wordpress 2018-07-19 20-50-21" src="https://user-images.githubusercontent.com/290886/42978960-5bb29a7e-8b95-11e8-8fdd-7a68fa08f33a.png">
Pretty Link - Social Warfare - Social Warfare

Advanced Custom Fields

Akismet Anti-Spam

BackUpWordPress

Beaver Builder Plugin (Pro Version)

Compress JPEG & PNG images
	
Google Analytics Dashboard for WP (GADWP)

iThemes Security

MiloTree Pop-up

Optimize Database after Deleting Revisions

Pretty Links

Safe Redirect Manager

SG Optimizer

Social Warfare

Social Warfare - Pro

Wordfence Security

WP Migrate DB

Select Yoast SEO Premium

**Comment by tnorthcutt** [comment]
Currently able to reproduce this on local for this customer: https://app.intercom.io/a/apps/e4n3xtxz/inbox/inbox/conversation/20948218266

Investigating.

**Comment by tnorthcutt** [comment]
Scratch that, not able to reproduce on local. Plugins this install has active:

- 404 to 301
- Ad Inserter
- Akismet
- Better Internal Link Search
- Classic Editor
- Comment Link Remove
- Contact Form 7
- ConvertKit
- Display Posts
- Easy Updates Manager
- EasyAzon
- EasyAzon Pro
- Envato Market
- GA Google Analytics
- GDPR Cookie Consent
- Heartbeat Control
- Inline Related Posts
- Interactive World Maps
- MailMunch
- MaxButtons
- Mediavine Control Panel
- Optin Forms
- POWr Social Media Icons
- Pretty Links
- Redirection
- Redux Framework
- Rel Nofollow Checkbox
- Shortcodes Indep
- Slider Revolution
- Smush
- Social Warfare
- Social Warfare - Pro
- SSL Insecure Content Fixer
- SumoMe
- Table of Contents Plus
- TheGem Theme Elements
- UpdraftPlus - Backup/Restore
- W3 Total Cache
- WordPress Page Widgets
- WP Hide Post
- WP Htaccess Editor
- WP RSS Images
- WPBakery Page Builder
- Yoast SEO
