### ISSUE TITLE
<a> link fails when page content is displayed on index, search, or category page

### ISSUE THREAD

**Issue by justinputney** [ConvertKit/ConvertKit-WordPress#9]
I understand that the modal links are limited to a specific post.

However, it very difficult to prevent the content of that post from appearing on another page within the same Wordpress site (_e.g._, index, search, category pages). In those cases, clicking the link does absolutely nothing.

This is a very unfortunate user experience. I've hidden much of the links behind "read more" tags, but it's so easy to break.

**Comment by growdev** [comment]
HI @justinputney thanks for submitting the issue. Can you provide an example of this so I can recreate it? 
Here's a form on a post on the left side with the index view on the right side. The form links aren't added. 
![screen shot 2016-03-28 at 10 20 02 am](https://cloud.githubusercontent.com/assets/290886/14081144/c1b082ec-f4ce-11e5-89c4-4b51c2a7319c.png)

**Comment by justinputney** [comment]
Hi @growdev,
Thanks for your reply. I'm referring specifically to modal links.
At the very bottom of [this page](ajarproductions.com/blog/page/14/?s=in5)—which is a search page—there's a grey box with a modal link. Click it and you'll that it does nothing. If you scroll up and click on the _About_ heading to get to the page itself, the link works inside the page.

**Comment by growdev** [comment]
The modal links will be revisited at a later time.
