### ISSUE TITLE
Add support for custom post types

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#90]
CK team requested adding support for Sensei courses (CPT: course). 

Check into adding a way for the site admin to select CPTs to add.

ref: https://secure.helpscout.net/conversation/508078989/160317?folderId=956509

**Comment by dylanfeltus** [comment]
https://nextplease.io/requests/338

**Comment by tnorthcutt** [comment]
Superseded by https://github.com/ConvertKit/ConvertKit-WordPress/issues/165

**Comment by jnthnclrk** [comment]
Is this now an option?
