### ISSUE TITLE
Reduce API calls in admin

### ISSUE THREAD

**Issue by growdev** [ConvertKit/ConvertKit-WordPress#91]
- [x] Check where the subscriber tracking JS is being used and remove where not needed. 
- [x] Maybe add an option to disable. 

ref: https://wordpress.org/support/topic/api-call-on-every-dashboard-page-load/

**Comment by defunctl** [comment]
Hey @growdev sorry I didn't make an issue, but really appreciate you looking into this!

Not sure if it needs to run on editing pages either, but it makes 4 requests when doing that as well:

![image](https://user-images.githubusercontent.com/1066195/34736258-95453e9c-f52f-11e7-931d-80ea1d61193e.png)

**Comment by growdev** [comment]
@defunctl no worries, and thanks for the screenshot.

**Comment by growdev** [comment]
@defunctl this is fixed in #99. Will go out in version 1.5.3 in a day or two.
